spring.application.name=SpringEnotes_Project
spring.datasource.url=jdbc:postgresql://localhost:5432/Enotes
spring.datasource.username=postgres
spring.datasource.password=Deepali
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
